### ISSUE TITLE
"Tools > App Actions" Doesn't Exist

### ISSUE THREAD

**Issue by RobbyCBennett** [actions-on-google/appactions-common-biis-kotlin#3]
I can't use the tool to view my app actions on Android Studio. I see XML Actions, but no App Actions.

**Comment by yoichiro** [comment]
@RobbyCBennett You need to install the Google Assistant Plugin to your Android Studio. See: [Install the test Plugin](https://codelabs.developers.google.com/codelabs/appactions-beta?hl=en&continue=https%3A%2F%2Fcodelabs.developers.google.com%2F#2)
After installing the plugin, you can find the "Google Assistant" menu in the "Tools" top menu.

![Screenshot_20210614_153736](https://user-images.githubusercontent.com/261787/121849667-952ae600-cd26-11eb-832d-18e332dda7b6.png)
